import { randomUUID } from "node:crypto";
import { Router } from "express";
import multer from "multer";
import { z } from "zod";
import { env } from "../../config/env.js";
import { query, queryOne } from "../../db/pool.js";
import { asyncRoute, badRequest, created, message, notFound, ok, validateBody } from "../../lib/api.js";
import { authenticate, requireAnyRole, requireRole } from "../../lib/auth.js";
import { booleanValue, firstString, optionalString, type JsonObject } from "../../lib/values.js";
import { publicCache } from "../../services/public-cache.js";
import { invalidatePublicCache, publicCdnCache, publicCdnPolicies } from "../../services/public-cdn-cache.js";
import { cloudinaryPublicIdFromUrl, deleteImage, uploadFile } from "../../services/storage.js";
import { acceptedStorageTypes, isPrivateStorageReference, storageService } from "../../services/blob-storage.js";

export const mediaRouter = Router();
// Compatibility multipart endpoints remain for small legacy clients. Files
// above this safe Function ceiling use the direct Blob authorization routes.
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: env.functionUploadMaxFileSize, files: 1 } });
const superAdmin = [authenticate, requireRole("SUPER_ADMIN")];
const admin = [authenticate, requireAnyRole("ADMIN", "SUPER_ADMIN")];
const param = (value: string | string[] | undefined): string => Array.isArray(value) ? value[0] ?? "" : value ?? "";
const invalidateGallery = async (): Promise<void> => {
  await invalidatePublicCache({ memoryGroups: ["media"], tags: ["gallery"] });
};
const invalidatePublicNotifications = async (): Promise<void> => {
  await invalidatePublicCache({ memoryGroups: ["media"], tags: ["public-notifications"] });
};
const bodySchema = z.object({
  id: z.string().trim().max(100).optional(), imageId: z.string().trim().max(60).optional(), notificationId: z.string().trim().max(60).optional(), keywordId: z.string().trim().max(60).optional(),
  title: z.string().trim().max(255).optional(), url: z.string().trim().max(2000).optional(), image: z.string().trim().max(2000).optional(), imageUrl: z.string().trim().max(2000).optional(), uploadedByType: z.string().trim().max(255).optional(), userId: z.string().trim().max(255).optional(),
  isApproved: z.union([z.boolean(),z.string(),z.number()]).optional(), approved: z.union([z.boolean(),z.string(),z.number()]).optional(), isFeatured: z.union([z.boolean(),z.string(),z.number()]).optional(), featured: z.union([z.boolean(),z.string(),z.number()]).optional(), featureConsent: z.union([z.boolean(),z.string(),z.number()]).optional(), publicFeatureConsent: z.union([z.boolean(),z.string(),z.number()]).optional(), allowPublicFeature: z.union([z.boolean(),z.string(),z.number()]).optional(),
  message: z.string().max(100000).optional(), description: z.string().max(100000).optional(), type: z.string().trim().max(255).optional(), targetType: z.string().trim().max(255).optional(), targetUser: z.string().trim().max(255).optional(), pdf: z.string().trim().max(2000).optional(), pdfUrl: z.string().trim().max(2000).optional(),
  keywords: z.string().max(100000).optional(), response: z.string().max(100000).optional(),
}).passthrough();
const directUploadSchema = z.object({
  filename: z.string().trim().min(1).max(255),
  contentType: z.string().trim().min(1).max(255),
  size: z.number().int().positive(),
  imageOnly: z.boolean().optional(),
});
const directFinalizeSchema = z.object({
  intent: z.string().min(1).max(6000),
  url: z.string().url().max(4000),
  title: z.string().trim().max(255).optional(),
});
const notificationDocumentSchema = z.object({
  filename: z.string().trim().min(1).max(255),
  contentType: z.literal("application/pdf"),
  size: z.number().int().positive(),
});

type Gallery={id:string;image_id:string;title:string;url:string;uploaded_by_type:string;user_id:string|null;approved:boolean;featured:boolean;feature_consent:boolean;user_name:string|null;user_code:string|null};
type Notification={id:string;notification_id:string;title:string;message:string|null;type:string|null;target_type:string;target_user_id:string|null;image_url:string|null;pdf_url:string|null;user_code:string|null;user_name:string|null};
type Keyword={id:string;keyword_id:string;type:string|null;keywords:string|null;response:string|null};
type Unanswered={id:string;question_id:string;question:string|null;response:string|null};
const mapGallery=(item:Gallery):Record<string,unknown>=>({id:item.id,_id:item.image_id,imageId:item.image_id,title:item.title,url:item.url,image:item.url,uploadedByType:item.uploaded_by_type,userId:item.user_code??"",userName:item.user_name??"",isApproved:item.approved,featureConsent:item.feature_consent,isFeatured:item.featured});
const mapGalleryForViewer=async(item:Gallery):Promise<Record<string,unknown>>=>{
  const mapped=mapGallery(item);
  if(!isPrivateStorageReference(item.url))return mapped;
  const url=await storageService.getDownloadAuthorization(item.url,"private");
  return {...mapped,url,image:url};
};
const mapNotification=(n:Notification,pdfUrl=n.pdf_url??""):Record<string,unknown>=>({id:n.notification_id,notificationId:n.notification_id,title:n.title,message:n.message??"",description:n.message??"",type:n.type??"",targetType:n.target_type,userId:n.user_code??"",target:n.user_code?`${n.user_code} (${n.user_name??""})`:"ALL USERS",image:n.image_url??"",imageUrl:n.image_url??"",pdf:pdfUrl,pdfUrl});
const mapNotificationForViewer=async(n:Notification):Promise<Record<string,unknown>>=>{
  if(!isPrivateStorageReference(n.pdf_url))return mapNotification(n);
  return mapNotification(n,await storageService.getDownloadAuthorization(n.pdf_url!,"private"));
};
const gallerySelect="SELECT g.*,u.name AS user_name,u.user_id AS user_code FROM gallery_images g LEFT JOIN app_users u ON u.id=g.user_id";
const notificationSelect="SELECT n.*,u.name AS user_name,u.user_id AS user_code FROM notifications n LEFT JOIN app_users u ON u.id=n.target_user_id";
const resolveUser=async(value:string):Promise<{id:string;user_id:string}>=>{const user=await queryOne<{id:string;user_id:string}>("SELECT id,user_id FROM app_users WHERE deleted=FALSE AND (user_id ILIKE $1 OR email ILIKE $1)",[value]);if(!user)throw notFound("User not found");return user;};

mediaRouter.post("/files",...admin,upload.single("file"),asyncRoute(async(request,response)=>{if(!request.file)throw badRequest("A file is required");const folder=typeof request.body.folder==="string"?request.body.folder:"general";const stored=await uploadFile(request.file,folder,booleanValue(request.body.imageOnly));response.status(201).json(created({url:stored.url}));}));
mediaRouter.post("/files/authorize-upload",...admin,validateBody(directUploadSchema),asyncRoute(async(request,response)=>{const body=request.body as z.infer<typeof directUploadSchema>;const allowed=body.imageOnly?acceptedStorageTypes.imageTypes:[...acceptedStorageTypes.imageTypes,...acceptedStorageTypes.pdfTypes,...acceptedStorageTypes.resumeTypes];const authorization=storageService.createUploadAuthorization({purpose:"public-media",access:"public",actorId:request.auth!.id,filename:body.filename,contentType:body.contentType,size:body.size,allowedContentTypes:allowed,maximumSizeInBytes:env.uploadMaxFileSize});response.json(ok(authorization));}));
mediaRouter.post("/files/finalize-upload",...admin,validateBody(directFinalizeSchema),asyncRoute(async(request,response)=>{const body=request.body as z.infer<typeof directFinalizeSchema>;const stored=await storageService.finalizeUpload(body.intent,body.url,request.auth!.id,"public-media");response.status(201).json(created({url:stored.url,contentType:stored.contentType,size:stored.size}));}));
mediaRouter.post("/notifications/authorize-document",...superAdmin,validateBody(notificationDocumentSchema),asyncRoute(async(request,response)=>{const body=request.body as z.infer<typeof notificationDocumentSchema>;const authorization=storageService.createUploadAuthorization({purpose:"notification-document",access:"private",actorId:request.auth!.id,filename:body.filename,contentType:body.contentType,size:body.size,allowedContentTypes:acceptedStorageTypes.pdfTypes,maximumSizeInBytes:env.privateAttachmentMaxFileSize});response.json(ok(authorization));}));
mediaRouter.post("/notifications/finalize-document",...superAdmin,validateBody(directFinalizeSchema),asyncRoute(async(request,response)=>{const body=request.body as z.infer<typeof directFinalizeSchema>;const stored=await storageService.finalizeUpload(body.intent,body.url,request.auth!.id,"notification-document");response.status(201).json(created({pdfUrl:stored.reference,contentType:stored.contentType,size:stored.size}));}));

mediaRouter.get("/gallery",...admin,asyncRoute(async(_request,response)=>response.json(ok(await Promise.all((await query<Gallery>(`${gallerySelect} WHERE g.deleted=FALSE ORDER BY g.created_at DESC`)).map(mapGalleryForViewer))))));
mediaRouter.get("/gallery/public",publicCdnCache(publicCdnPolicies.gallery,["gallery"]),asyncRoute(async(_request,response)=>{const data=await publicCache.getOrLoad("media:gallery",async()=> Promise.all((await query<Gallery>(`${gallerySelect} WHERE g.deleted=FALSE AND g.approved=TRUE AND g.featured=TRUE AND g.feature_consent=TRUE ORDER BY g.created_at DESC`)).map(mapGalleryForViewer)));response.json(ok(data));}));
mediaRouter.get("/get-photos",authenticate,asyncRoute(async(request,response)=>{const records=await query<Gallery>(`${gallerySelect} WHERE g.deleted=FALSE AND g.user_id=$1 ORDER BY g.created_at DESC`,[request.auth!.id]);response.json(ok(await Promise.all(records.map(mapGalleryForViewer))));}));
const findGallery=async(value:string):Promise<Gallery>=>{const row=await queryOne<Gallery>(`${gallerySelect} WHERE g.deleted=FALSE AND (g.id::text=$1 OR g.image_id ILIKE $1)`,[value]);if(!row)throw notFound("Image not found");return row;};
const writeGallery=async(id:string,body:JsonObject,existing?:Gallery,userId?:string):Promise<Gallery>=>{const imageId=firstString(body,"imageId","id")||existing?.image_id||`IMG${Date.now()}`;const title=firstString(body,"title")||existing?.title||imageId;const url=firstString(body,"url","image")||existing?.url||"";if(!url)throw new Error("Image URL is required");const uploadedByType=firstString(body,"uploadedByType")||existing?.uploaded_by_type||(userId?"user":"admin");let ownerId=userId??existing?.user_id??null;if(!ownerId&&firstString(body,"userId"))ownerId=(await resolveUser(firstString(body,"userId"))).id;let consent=body.featureConsent===undefined&&body.publicFeatureConsent===undefined&&body.allowPublicFeature===undefined?(existing?.feature_consent??!userId):booleanValue(body.featureConsent??body.publicFeatureConsent??body.allowPublicFeature);if(uploadedByType.toLowerCase()!=="user")consent=true;const approved=body.approved===undefined&&body.isApproved===undefined?(existing?.approved??true):booleanValue(body.approved??body.isApproved);const proposedFeatured=body.featured===undefined&&body.isFeatured===undefined?(existing?.featured??false):booleanValue(body.featured??body.isFeatured);const featured=consent&&proposedFeatured;if(existing)await queryOne("UPDATE gallery_images SET image_id=$1,title=$2,url=$3,uploaded_by_type=$4,user_id=$5,approved=$6,featured=$7,feature_consent=$8,updated_at=NOW() WHERE id=$9",[imageId,title,url,uploadedByType,ownerId,approved,featured,consent,id]);else await queryOne("INSERT INTO gallery_images (id,created_at,updated_at,deleted,image_id,title,url,uploaded_by_type,user_id,approved,featured,feature_consent) VALUES ($1,NOW(),NOW(),FALSE,$2,$3,$4,$5,$6,$7,$8,$9)",[id,imageId,title,url,uploadedByType,ownerId,approved,featured,consent]);return findGallery(id);};
mediaRouter.post("/gallery",...superAdmin,validateBody(bodySchema),asyncRoute(async(request,response)=>{const image=await writeGallery(randomUUID(),request.body as JsonObject);await invalidateGallery();response.status(201).json(created(mapGallery(image)));}));
mediaRouter.put("/gallery/:imageId",...superAdmin,validateBody(bodySchema),asyncRoute(async(request,response)=>{const old=await findGallery(param(request.params.imageId));const image=await writeGallery(old.id,request.body as JsonObject,old);await invalidateGallery();response.json(ok(mapGallery(image)));}));
const removeGalleryObject=async(item:Gallery):Promise<void>=>{if(isPrivateStorageReference(item.url))await storageService.deleteObject(item.url,"private");else await deleteImage(cloudinaryPublicIdFromUrl(item.url));};
const savePrivatePhoto=async(input:{userId:string;title:string;contentType:string;filename:string;size:number;buffer?:Buffer;intent?:string;url?:string}):Promise<Gallery>=>{let reference:string;if(input.buffer){if(!acceptedStorageTypes.imageTypes.includes(input.contentType as (typeof acceptedStorageTypes.imageTypes)[number]))throw badRequest("Only JPEG, PNG, and WebP images are supported");const authorization=storageService.createUploadAuthorization({purpose:"travel-photo",access:"private",actorId:input.userId,filename:input.filename,contentType:input.contentType,size:input.size,allowedContentTypes:acceptedStorageTypes.imageTypes,maximumSizeInBytes:env.uploadMaxFileSize});reference=(await storageService.putSmallObject({access:"private",pathname:authorization.pathname,buffer:input.buffer,contentType:input.contentType})).reference;}else{if(!input.intent||!input.url)throw badRequest("A completed upload is required");reference=(await storageService.finalizeUpload(input.intent,input.url,input.userId,"travel-photo")).reference;}return writeGallery(randomUUID(),{title:input.title,url:reference,uploadedByType:"user",featureConsent:false,isApproved:false,isFeatured:false},undefined,input.userId);};
mediaRouter.post("/upload-photo/authorize",authenticate,validateBody(directUploadSchema),asyncRoute(async(request,response)=>{const body=request.body as z.infer<typeof directUploadSchema>;const authorization=storageService.createUploadAuthorization({purpose:"travel-photo",access:"private",actorId:request.auth!.id,filename:body.filename,contentType:body.contentType,size:body.size,allowedContentTypes:acceptedStorageTypes.imageTypes,maximumSizeInBytes:env.uploadMaxFileSize});response.json(ok(authorization));}));
mediaRouter.post("/upload-photo/finalize",authenticate,validateBody(directFinalizeSchema),asyncRoute(async(request,response)=>{const body=request.body as z.infer<typeof directFinalizeSchema>;const item=await savePrivatePhoto({userId:request.auth!.id,title:body.title??"",contentType:"",filename:"",size:0,intent:body.intent,url:body.url});response.status(201).json(created(await mapGalleryForViewer(item)));}));
mediaRouter.delete("/gallery/:imageId",...superAdmin,asyncRoute(async(request,response)=>{const item=await findGallery(param(request.params.imageId));await removeGalleryObject(item);await queryOne("DELETE FROM gallery_images WHERE id=$1",[item.id]);await invalidateGallery();response.json(message("Gallery image deleted"));}));
mediaRouter.post("/upload-photo",authenticate,upload.single("file"),asyncRoute(async(request,response)=>{if(!request.file)throw badRequest("An image file is required");const item=await savePrivatePhoto({userId:request.auth!.id,title:typeof request.body.title==="string"?request.body.title:"",contentType:request.file.mimetype,filename:request.file.originalname,size:request.file.size,buffer:request.file.buffer});response.status(201).json(created(await mapGalleryForViewer(item)));}));
mediaRouter.delete("/delete-photo/:imageId",authenticate,asyncRoute(async(request,response)=>{const item=await findGallery(param(request.params.imageId));if(item.user_id!==request.auth!.id&&request.auth!.role!=="SUPER_ADMIN")throw notFound("Image not found");await removeGalleryObject(item);await queryOne("DELETE FROM gallery_images WHERE id=$1",[item.id]);await invalidateGallery();response.json(message("Gallery image deleted"));}));

mediaRouter.get("/notifications",...admin,asyncRoute(async(_request,response)=>response.json(ok(await Promise.all((await query<Notification>(`${notificationSelect} WHERE n.deleted=FALSE ORDER BY n.created_at DESC`)).map(mapNotificationForViewer))))));
mediaRouter.get("/notifications/public",publicCdnCache(publicCdnPolicies.publicNotifications,["public-notifications"]),asyncRoute(async(_request,response)=>{const data=await publicCache.getOrLoad("media:notifications",async()=> Promise.all((await query<Notification>(`${notificationSelect} WHERE n.deleted=FALSE AND LOWER(n.target_type) IN ('all','public') ORDER BY n.created_at DESC`)).map(mapNotificationForViewer)));response.json(ok(data));}));
mediaRouter.get("/notifications/me",authenticate,asyncRoute(async(request,response)=>response.json(ok(await Promise.all((await query<Notification>(`${notificationSelect} WHERE n.deleted=FALSE AND (LOWER(n.target_type) IN ('all','public') OR n.target_user_id=$1) ORDER BY n.created_at DESC`,[request.auth!.id])).map(mapNotificationForViewer))))));
const findNotification=async(value:string):Promise<Notification>=>{const row=await queryOne<Notification>(`${notificationSelect} WHERE n.deleted=FALSE AND (n.notification_id ILIKE $1 OR n.id::text=$1)`,[value]);if(!row)throw notFound("Notification not found");return row;};
const writeNotification=async(id:string,body:JsonObject,existing?:Notification):Promise<Notification>=>{const notificationId=firstString(body,"notificationId","id")||existing?.notification_id||`NOT${Date.now()}`;const target=firstString(body,"userId","targetUser");const targetUser=target&&target.toUpperCase()!=="ALL USERS"?await resolveUser(target):undefined;const targetType=targetUser?"user":firstString(body,"targetType")||existing?.target_type||"all";const title=firstString(body,"title")||existing?.title||notificationId;if(existing)await queryOne("UPDATE notifications SET notification_id=$1,title=$2,message=$3,type=$4,target_type=$5,target_user_id=$6,image_url=$7,pdf_url=$8,updated_at=NOW() WHERE id=$9",[notificationId,title,optionalString(body,"message","description"),optionalString(body,"type"),targetType,targetUser?.id??null,optionalString(body,"imageUrl","image"),optionalString(body,"pdfUrl","pdf"),id]);else await queryOne("INSERT INTO notifications (id,created_at,updated_at,deleted,notification_id,title,message,type,target_type,target_user_id,image_url,pdf_url) VALUES ($1,NOW(),NOW(),FALSE,$2,$3,$4,$5,$6,$7,$8,$9)",[id,notificationId,title,optionalString(body,"message","description"),optionalString(body,"type"),targetType,targetUser?.id??null,optionalString(body,"imageUrl","image"),optionalString(body,"pdfUrl","pdf")]);return findNotification(id);};
mediaRouter.post("/notifications",...superAdmin,validateBody(bodySchema),asyncRoute(async(request,response)=>{const notification=await writeNotification(randomUUID(),request.body as JsonObject);await invalidatePublicNotifications();response.status(201).json(created(await mapNotificationForViewer(notification)));}));
mediaRouter.put("/notifications/:id",...superAdmin,validateBody(bodySchema),asyncRoute(async(request,response)=>{const old=await findNotification(param(request.params.id));const notification=await writeNotification(old.id,request.body as JsonObject,old);await invalidatePublicNotifications();response.json(ok(await mapNotificationForViewer(notification)));}));
mediaRouter.delete("/notifications/:id",...superAdmin,asyncRoute(async(request,response)=>{const old=await findNotification(param(request.params.id));await queryOne("DELETE FROM notifications WHERE id=$1",[old.id]);if(isPrivateStorageReference(old.pdf_url))await storageService.deleteObject(old.pdf_url!,"private");await invalidatePublicNotifications();response.json(message("Notification deleted"));}));

const mapKeyword=(item:Keyword):Record<string,unknown>=>({id:item.keyword_id,type:item.type??"",keywords:item.keywords??"",response:item.response??""});
const findKeyword=async(value:string):Promise<Keyword>=>{const row=await queryOne<Keyword>("SELECT * FROM keywords WHERE deleted=FALSE AND (keyword_id ILIKE $1 OR id::text=$1)",[value]);if(!row)throw notFound("Keyword not found");return row;};
mediaRouter.get("/keywords",...admin,asyncRoute(async(_request,response)=>response.json(ok((await query<Keyword>("SELECT * FROM keywords WHERE deleted=FALSE ORDER BY type")).map(mapKeyword)))));
mediaRouter.post("/keywords",...superAdmin,validateBody(bodySchema),asyncRoute(async(request,response)=>{const body=request.body as JsonObject;const id=randomUUID();await queryOne("INSERT INTO keywords (id,created_at,updated_at,deleted,keyword_id,type,keywords,response) VALUES ($1,NOW(),NOW(),FALSE,$2,$3,$4,$5)",[id,firstString(body,"id","keywordId")||`KEY${Date.now()}`,optionalString(body,"type"),optionalString(body,"keywords"),optionalString(body,"response")]);response.status(201).json(created(mapKeyword(await findKeyword(id))));}));
mediaRouter.put("/keywords/:id",...superAdmin,validateBody(bodySchema),asyncRoute(async(request,response)=>{const key=await findKeyword(param(request.params.id));const body=request.body as JsonObject;await queryOne("UPDATE keywords SET type=$1,keywords=$2,response=$3,updated_at=NOW() WHERE id=$4",[optionalString(body,"type"),optionalString(body,"keywords"),optionalString(body,"response"),key.id]);response.json(ok(mapKeyword(await findKeyword(key.id))));}));
mediaRouter.delete("/keywords/:id",...superAdmin,asyncRoute(async(request,response)=>{const key=await findKeyword(param(request.params.id));await queryOne("DELETE FROM keywords WHERE id=$1",[key.id]);response.json(message("Keyword deleted"));}));

const mapUnanswered=(item:Unanswered):Record<string,unknown>=>({id:item.question_id,question:item.question??"",response:item.response??""});
const findUnanswered=async(value:string):Promise<Unanswered>=>{const row=await queryOne<Unanswered>("SELECT * FROM unanswered_questions WHERE deleted=FALSE AND (question_id ILIKE $1 OR id::text=$1)",[value]);if(!row)throw notFound("Question not found");return row;};
mediaRouter.get("/unanswered",...admin,asyncRoute(async(_request,response)=>response.json(ok((await query<Unanswered>("SELECT * FROM unanswered_questions WHERE deleted=FALSE ORDER BY created_at DESC")).map(mapUnanswered)))));
mediaRouter.post("/unanswered/:id/answer",...superAdmin,validateBody(bodySchema),asyncRoute(async(request,response)=>{const item=await findUnanswered(param(request.params.id));await queryOne("UPDATE unanswered_questions SET response=$1,deleted=TRUE,updated_at=NOW() WHERE id=$2",[optionalString(request.body as JsonObject,"response"),item.id]);response.json(message("Question answered"));}));
mediaRouter.delete("/unanswered/:id",...superAdmin,asyncRoute(async(request,response)=>{const item=await findUnanswered(param(request.params.id));await queryOne("DELETE FROM unanswered_questions WHERE id=$1",[item.id]);response.json(message("Question deleted"));}));
