import { randomUUID } from "node:crypto";
import { Router } from "express";
import { z } from "zod";
import { query, queryOne } from "../../db/pool.js";
import { asyncRoute, badRequest, message, notFound, ok, validateBody } from "../../lib/api.js";
import { authenticate, optionalAuthenticate, requireAnyRole } from "../../lib/auth.js";
import { isoDate, stringValue } from "../../lib/values.js";
import { mapPackageSummary } from "../catalog/mapper.js";
import { packageByIdentifier } from "../catalog/repository.js";

export const analyticsRouter = Router();
const admin = [authenticate, requireAnyRole("ADMIN", "SUPER_ADMIN")];
const param = (value: string | string[] | undefined): string => Array.isArray(value) ? value[0] ?? "" : value ?? "";
const bodySchema = z.object({ packageCode: z.string().trim().min(1).max(60).optional(), code: z.string().trim().min(1).max(60).optional(), sessionIdentifier: z.string().trim().max(120).optional(), sessionId: z.string().trim().max(120).optional() });
type View={id:string;user_id:string|null;session_identifier:string|null;package_id:string;view_count:number;first_viewed_at:Date|string;last_viewed_at:Date|string;hidden_from_user:boolean;user_code:string|null;user_name:string|null;package_code:string};
const viewSelect="SELECT h.*,u.user_id AS user_code,u.name AS user_name,p.package_code FROM package_view_histories h JOIN travel_packages p ON p.id=h.package_id LEFT JOIN app_users u ON u.id=h.user_id";
const mapView=async(view:View):Promise<Record<string,unknown>>=>{const pkg=mapPackageSummary(await packageByIdentifier(view.package_id));return{...pkg,id:view.id,viewCount:view.view_count,firstViewedAt:isoDate(view.first_viewed_at),lastViewedAt:isoDate(view.last_viewed_at),viewerType:view.user_id?"USER":"GUEST",sessionIdentifier:view.session_identifier??"",userId:view.user_code??"",userName:view.user_name??""};};
const page=(value:unknown,defaultValue:number,max:number)=>Math.min(max,Math.max(0,Number.parseInt(typeof value==="string"?value:String(defaultValue),10)||defaultValue));
const pageResult=async<T>(sql:string,values:unknown[],pageNumber:number,size:number):Promise<{content:T[];page:number;size:number;totalElements:number;totalPages:number}>=>{const rows=await query<T & {total_count:string}>(`${sql} LIMIT $${values.length+1} OFFSET $${values.length+2}`,[...values,size,pageNumber*size]);const total=Number(rows[0]?.total_count??0);return{content:rows.map(({total_count:_,...item})=>item as T),page:pageNumber,size,totalElements:total,totalPages:Math.ceil(total/size)};};

analyticsRouter.post("/package-views",optionalAuthenticate,validateBody(bodySchema),asyncRoute(async(request,response)=>{const body=request.body as z.infer<typeof bodySchema>;const pkg=await packageByIdentifier(body.packageCode||body.code||"");const now=new Date();let id:string;if(request.auth){const row=await queryOne<{id:string}>(`INSERT INTO package_view_histories (id,created_at,updated_at,deleted,user_id,package_id,session_identifier,view_count,first_viewed_at,last_viewed_at,hidden_from_user) VALUES ($1,$2,$2,FALSE,$3,$4,NULL,1,$2,$2,FALSE) ON CONFLICT (user_id,package_id) WHERE user_id IS NOT NULL DO UPDATE SET deleted=FALSE,hidden_from_user=FALSE,view_count=package_view_histories.view_count+1,last_viewed_at=EXCLUDED.last_viewed_at,updated_at=EXCLUDED.updated_at RETURNING id`,[randomUUID(),now,request.auth.id,pkg.id]);id=row!.id;}else{const session=(body.sessionIdentifier||body.sessionId||randomUUID()).slice(0,120);const row=await queryOne<{id:string}>(`INSERT INTO package_view_histories (id,created_at,updated_at,deleted,user_id,package_id,session_identifier,view_count,first_viewed_at,last_viewed_at,hidden_from_user) VALUES ($1,$2,$2,FALSE,NULL,$3,$4,1,$2,$2,FALSE) ON CONFLICT (session_identifier,package_id) WHERE user_id IS NULL DO UPDATE SET deleted=FALSE,view_count=package_view_histories.view_count+1,last_viewed_at=EXCLUDED.last_viewed_at,updated_at=EXCLUDED.updated_at RETURNING id`,[randomUUID(),now,pkg.id,session]);id=row!.id;}const view=await queryOne<View>(`${viewSelect} WHERE h.id=$1`,[id]);if(!view)throw new Error("View could not be recorded");response.json(ok(await mapView(view)));}));
analyticsRouter.get("/package-views/me",authenticate,asyncRoute(async(request,response)=>{const views=await query<View>(`${viewSelect} WHERE h.user_id=$1 AND h.deleted=FALSE AND h.hidden_from_user=FALSE ORDER BY h.last_viewed_at DESC`,[request.auth!.id]);response.json(ok(await Promise.all(views.map(mapView))));}));
analyticsRouter.delete("/package-views/me/:packageCode",authenticate,asyncRoute(async(request,response)=>{const pkg=await packageByIdentifier(param(request.params.packageCode));await queryOne("UPDATE package_view_histories SET hidden_from_user=TRUE,updated_at=NOW() WHERE user_id=$1 AND package_id=$2",[request.auth!.id,pkg.id]);response.json(message("Package removed from recently viewed history"));}));
analyticsRouter.delete("/package-views/me",authenticate,asyncRoute(async(request,response)=>{await queryOne("UPDATE package_view_histories SET hidden_from_user=TRUE,updated_at=NOW() WHERE user_id=$1 AND deleted=FALSE",[request.auth!.id]);response.json(message("Recently viewed history cleared"));}));

analyticsRouter.get("/package-views/analytics",...admin,asyncRoute(async(request,response)=>{const viewerType=stringValue(request.query.viewerType).toUpperCase();const where=["h.deleted=FALSE"];if(viewerType==="USER")where.push("h.user_id IS NOT NULL");if(viewerType==="GUEST")where.push("h.user_id IS NULL");const views=await query<View>(`${viewSelect} WHERE ${where.join(" AND ")} ORDER BY h.last_viewed_at DESC`);const histories=await Promise.all(views.map(mapView));const grouped=new Map<string,Record<string,unknown>>();for(const item of histories){const code=String(item.packageCode);const prior=grouped.get(code)??{...item,totalViews:0};prior.totalViews=Number(prior.totalViews)+Number(item.viewCount);grouped.set(code,prior);}response.json(ok({histories,popularPackages:[...grouped.values()].sort((a,b)=>Number(b.totalViews)-Number(a.totalViews)).slice(0,10),summary:{totalViews:histories.reduce((total,item)=>total+Number(item.viewCount),0),loggedInRecords:histories.filter(item=>item.viewerType==="USER").length,ghostRecords:histories.filter(item=>item.viewerType==="GUEST").length}}));}));
analyticsRouter.get("/package-views/viewers",...admin,asyncRoute(async(request,response)=>{const viewerType=stringValue(request.query.viewerType).toUpperCase();const search=stringValue(request.query.search);const pageNumber=page(request.query.page,0,100000);const size=Math.min(100,Math.max(1,page(request.query.size,10,100)));const typeClause=viewerType==="USER"?"h.user_id IS NOT NULL":viewerType==="GUEST"?"h.user_id IS NULL":"TRUE";const sql=`SELECT CASE WHEN h.user_id IS NULL THEN h.session_identifier ELSE u.user_id END AS "viewerIdentifier",CASE WHEN h.user_id IS NULL THEN 'GUEST' ELSE 'USER' END AS "viewerType",COALESCE(u.user_id,'') AS "userId",COALESCE(u.name,'') AS "viewerName",COUNT(DISTINCT h.package_id)::bigint AS "distinctPackageCount",SUM(h.view_count)::bigint AS "totalViewCount",MIN(h.first_viewed_at) AS "firstActivityAt",MAX(h.last_viewed_at) AS "lastActivityAt",COUNT(*) OVER()::text AS total_count FROM package_view_histories h LEFT JOIN app_users u ON u.id=h.user_id WHERE h.deleted=FALSE AND ${typeClause} AND ($1='' OR LOWER(COALESCE(u.user_id,h.session_identifier,'')) LIKE LOWER($2) OR LOWER(COALESCE(u.name,'')) LIKE LOWER($2)) GROUP BY h.user_id,h.session_identifier,u.user_id,u.name ORDER BY MAX(h.last_viewed_at) DESC`;response.json(ok(await pageResult(sql,[search,`%${search}%`],pageNumber,size)));}));
analyticsRouter.get("/package-views/guest-packages",...admin,asyncRoute(async(request,response)=>{const limit=Math.min(12,Math.max(1,page(request.query.limit,8,12)));const rows=await query<Record<string,unknown>>(`SELECT p.id AS "packageId",p.package_code AS "packageCode",COALESCE(p.short_title,p.hero_title) AS "packageName",COUNT(DISTINCT h.session_identifier)::bigint AS "guestViewerCount",SUM(h.view_count)::bigint AS "totalViewCount",MAX(h.last_viewed_at) AS "lastViewedAt" FROM package_view_histories h JOIN travel_packages p ON p.id=h.package_id WHERE h.deleted=FALSE AND h.user_id IS NULL GROUP BY p.id,p.package_code,p.short_title,p.hero_title ORDER BY SUM(h.view_count) DESC LIMIT $1`,[limit]);response.json(ok(rows));}));
analyticsRouter.get("/package-views/guest-packages/:packageCode/viewers",...admin,asyncRoute(async(request,response)=>{const pageNumber=page(request.query.page,0,100000);const size=Math.min(100,Math.max(1,page(request.query.size,10,100)));const sql=`SELECT h.session_identifier AS "viewerIdentifier",h.view_count AS "viewCount",h.first_viewed_at AS "firstViewedAt",h.last_viewed_at AS "lastViewedAt",COUNT(*) OVER()::text AS total_count FROM package_view_histories h JOIN travel_packages p ON p.id=h.package_id WHERE h.deleted=FALSE AND h.user_id IS NULL AND p.package_code ILIKE $1 ORDER BY h.last_viewed_at DESC`;response.json(ok(await pageResult(sql,[param(request.params.packageCode)],pageNumber,size)));}));
analyticsRouter.get("/package-views/viewers/:viewerIdentifier/packages",...admin,asyncRoute(async(request,response)=>{const identifier=param(request.params.viewerIdentifier);const type=stringValue(request.query.viewerType).toUpperCase();if(!["USER","GUEST"].includes(type))throw badRequest("Viewer type must be USER or GUEST");const pageNumber=page(request.query.page,0,100000);const size=Math.min(100,Math.max(1,page(request.query.size,10,100)));const condition=type==="USER"?"u.user_id ILIKE $1":"h.session_identifier=$1";const sql=`SELECT p.id AS "packageId",p.package_code AS "packageCode",COALESCE(p.short_title,p.hero_title) AS "packageName",'' AS "parentCategories",'' AS subcategories,h.view_count AS "viewCount",h.first_viewed_at AS "firstViewedAt",h.last_viewed_at AS "lastViewedAt",COUNT(*) OVER()::text AS total_count FROM package_view_histories h JOIN travel_packages p ON p.id=h.package_id LEFT JOIN app_users u ON u.id=h.user_id WHERE h.deleted=FALSE AND ${condition} ORDER BY h.last_viewed_at DESC`;response.json(ok(await pageResult(sql,[identifier],pageNumber,size)));}));
